# Generated by Django 5.1.2 on 2025-01-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mes_anio',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
    ]
